// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBsKZSADhdcZOoVGFu1CiEY2b5NYx4PK8',
    appId: '1:1002617271969:web:220964fc21734993d5e2e0',
    messagingSenderId: '1002617271969',
    projectId: 'fir-privex',
    authDomain: 'fir-privex.firebaseapp.com',
    storageBucket: 'fir-privex.firebasestorage.app',
    measurementId: 'G-S8JN406B7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoO-tdMdE-ADfsFU4Un63YaocEHZN7yC0',
    appId: '1:1002617271969:android:f575b5f6432fe592d5e2e0',
    messagingSenderId: '1002617271969',
    projectId: 'fir-privex',
    storageBucket: 'fir-privex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc7MSvh5nC54biyBa-MF9lzuAI7H9cXDs',
    appId: '1:1002617271969:ios:2e43326d4afe7d0dd5e2e0',
    messagingSenderId: '1002617271969',
    projectId: 'fir-privex',
    storageBucket: 'fir-privex.firebasestorage.app',
    iosBundleId: 'com.example.privex',
  );
}
