import 'package:firebase_core/firebase_core.dart';
import 'package:privex/firebase_options.dart';

Future<void> setupFirebase() async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // This is a placeholder for the code that will be generated by the next steps.
}
